// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// EmailCredential is the predicate function for emailcredential builders.
type EmailCredential func(*sql.Selector)

// LoginSession is the predicate function for loginsession builders.
type LoginSession func(*sql.Selector)

// SuperuserProfile is the predicate function for superuserprofile builders.
type SuperuserProfile func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserPublicProfile is the predicate function for userpublicprofile builders.
type UserPublicProfile func(*sql.Selector)
