projects:
  GraphQL Main:
    schemaPath: src/graphql/schema.json
    includes:
      - src/**/*.graphql.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src
        region: ap-northeast-1
        apiId: nf6xrjpmbjfzjdg4fhvndyl3bm
        maxDepth: 10
extensions:
  amplify:
    version: 3
