// Code generated by ent, DO NOT EDIT.

package entgenerated

import (
	"api/ent/entgenerated/emailcredential"
	"api/ent/entgenerated/predicate"
	"api/ent/entgenerated/user"
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EmailCredentialQuery is the builder for querying EmailCredential entities.
type EmailCredentialQuery struct {
	config
	ctx        *QueryContext
	order      []emailcredential.OrderOption
	inters     []Interceptor
	predicates []predicate.EmailCredential
	withOwner  *UserQuery
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*EmailCredential) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EmailCredentialQuery builder.
func (ecq *EmailCredentialQuery) Where(ps ...predicate.EmailCredential) *EmailCredentialQuery {
	ecq.predicates = append(ecq.predicates, ps...)
	return ecq
}

// Limit the number of records to be returned by this query.
func (ecq *EmailCredentialQuery) Limit(limit int) *EmailCredentialQuery {
	ecq.ctx.Limit = &limit
	return ecq
}

// Offset to start from.
func (ecq *EmailCredentialQuery) Offset(offset int) *EmailCredentialQuery {
	ecq.ctx.Offset = &offset
	return ecq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ecq *EmailCredentialQuery) Unique(unique bool) *EmailCredentialQuery {
	ecq.ctx.Unique = &unique
	return ecq
}

// Order specifies how the records should be ordered.
func (ecq *EmailCredentialQuery) Order(o ...emailcredential.OrderOption) *EmailCredentialQuery {
	ecq.order = append(ecq.order, o...)
	return ecq
}

// QueryOwner chains the current query on the "owner" edge.
func (ecq *EmailCredentialQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: ecq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ecq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ecq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(emailcredential.Table, emailcredential.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, emailcredential.OwnerTable, emailcredential.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(ecq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EmailCredential entity from the query.
// Returns a *NotFoundError when no EmailCredential was found.
func (ecq *EmailCredentialQuery) First(ctx context.Context) (*EmailCredential, error) {
	nodes, err := ecq.Limit(1).All(setContextOp(ctx, ecq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{emailcredential.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ecq *EmailCredentialQuery) FirstX(ctx context.Context) *EmailCredential {
	node, err := ecq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EmailCredential ID from the query.
// Returns a *NotFoundError when no EmailCredential ID was found.
func (ecq *EmailCredentialQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ecq.Limit(1).IDs(setContextOp(ctx, ecq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{emailcredential.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ecq *EmailCredentialQuery) FirstIDX(ctx context.Context) int {
	id, err := ecq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EmailCredential entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EmailCredential entity is found.
// Returns a *NotFoundError when no EmailCredential entities are found.
func (ecq *EmailCredentialQuery) Only(ctx context.Context) (*EmailCredential, error) {
	nodes, err := ecq.Limit(2).All(setContextOp(ctx, ecq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{emailcredential.Label}
	default:
		return nil, &NotSingularError{emailcredential.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ecq *EmailCredentialQuery) OnlyX(ctx context.Context) *EmailCredential {
	node, err := ecq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EmailCredential ID in the query.
// Returns a *NotSingularError when more than one EmailCredential ID is found.
// Returns a *NotFoundError when no entities are found.
func (ecq *EmailCredentialQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ecq.Limit(2).IDs(setContextOp(ctx, ecq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{emailcredential.Label}
	default:
		err = &NotSingularError{emailcredential.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ecq *EmailCredentialQuery) OnlyIDX(ctx context.Context) int {
	id, err := ecq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EmailCredentials.
func (ecq *EmailCredentialQuery) All(ctx context.Context) ([]*EmailCredential, error) {
	ctx = setContextOp(ctx, ecq.ctx, "All")
	if err := ecq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EmailCredential, *EmailCredentialQuery]()
	return withInterceptors[[]*EmailCredential](ctx, ecq, qr, ecq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ecq *EmailCredentialQuery) AllX(ctx context.Context) []*EmailCredential {
	nodes, err := ecq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EmailCredential IDs.
func (ecq *EmailCredentialQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ecq.ctx.Unique == nil && ecq.path != nil {
		ecq.Unique(true)
	}
	ctx = setContextOp(ctx, ecq.ctx, "IDs")
	if err = ecq.Select(emailcredential.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ecq *EmailCredentialQuery) IDsX(ctx context.Context) []int {
	ids, err := ecq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ecq *EmailCredentialQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ecq.ctx, "Count")
	if err := ecq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ecq, querierCount[*EmailCredentialQuery](), ecq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ecq *EmailCredentialQuery) CountX(ctx context.Context) int {
	count, err := ecq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ecq *EmailCredentialQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ecq.ctx, "Exist")
	switch _, err := ecq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("entgenerated: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ecq *EmailCredentialQuery) ExistX(ctx context.Context) bool {
	exist, err := ecq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EmailCredentialQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ecq *EmailCredentialQuery) Clone() *EmailCredentialQuery {
	if ecq == nil {
		return nil
	}
	return &EmailCredentialQuery{
		config:     ecq.config,
		ctx:        ecq.ctx.Clone(),
		order:      append([]emailcredential.OrderOption{}, ecq.order...),
		inters:     append([]Interceptor{}, ecq.inters...),
		predicates: append([]predicate.EmailCredential{}, ecq.predicates...),
		withOwner:  ecq.withOwner.Clone(),
		// clone intermediate query.
		sql:  ecq.sql.Clone(),
		path: ecq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (ecq *EmailCredentialQuery) WithOwner(opts ...func(*UserQuery)) *EmailCredentialQuery {
	query := (&UserClient{config: ecq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ecq.withOwner = query
	return ecq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		OwnerID int `json:"owner_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EmailCredential.Query().
//		GroupBy(emailcredential.FieldOwnerID).
//		Aggregate(entgenerated.Count()).
//		Scan(ctx, &v)
func (ecq *EmailCredentialQuery) GroupBy(field string, fields ...string) *EmailCredentialGroupBy {
	ecq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EmailCredentialGroupBy{build: ecq}
	grbuild.flds = &ecq.ctx.Fields
	grbuild.label = emailcredential.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		OwnerID int `json:"owner_id,omitempty"`
//	}
//
//	client.EmailCredential.Query().
//		Select(emailcredential.FieldOwnerID).
//		Scan(ctx, &v)
func (ecq *EmailCredentialQuery) Select(fields ...string) *EmailCredentialSelect {
	ecq.ctx.Fields = append(ecq.ctx.Fields, fields...)
	sbuild := &EmailCredentialSelect{EmailCredentialQuery: ecq}
	sbuild.label = emailcredential.Label
	sbuild.flds, sbuild.scan = &ecq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EmailCredentialSelect configured with the given aggregations.
func (ecq *EmailCredentialQuery) Aggregate(fns ...AggregateFunc) *EmailCredentialSelect {
	return ecq.Select().Aggregate(fns...)
}

func (ecq *EmailCredentialQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ecq.inters {
		if inter == nil {
			return fmt.Errorf("entgenerated: uninitialized interceptor (forgotten import entgenerated/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ecq); err != nil {
				return err
			}
		}
	}
	for _, f := range ecq.ctx.Fields {
		if !emailcredential.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("entgenerated: invalid field %q for query", f)}
		}
	}
	if ecq.path != nil {
		prev, err := ecq.path(ctx)
		if err != nil {
			return err
		}
		ecq.sql = prev
	}
	if emailcredential.Policy == nil {
		return errors.New("entgenerated: uninitialized emailcredential.Policy (forgotten import entgenerated/runtime?)")
	}
	if err := emailcredential.Policy.EvalQuery(ctx, ecq); err != nil {
		return err
	}
	return nil
}

func (ecq *EmailCredentialQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EmailCredential, error) {
	var (
		nodes       = []*EmailCredential{}
		_spec       = ecq.querySpec()
		loadedTypes = [1]bool{
			ecq.withOwner != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EmailCredential).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EmailCredential{config: ecq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(ecq.modifiers) > 0 {
		_spec.Modifiers = ecq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ecq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ecq.withOwner; query != nil {
		if err := ecq.loadOwner(ctx, query, nodes, nil,
			func(n *EmailCredential, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	for i := range ecq.loadTotal {
		if err := ecq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ecq *EmailCredentialQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*EmailCredential, init func(*EmailCredential), assign func(*EmailCredential, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*EmailCredential)
	for i := range nodes {
		fk := nodes[i].OwnerID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "owner_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ecq *EmailCredentialQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ecq.querySpec()
	if len(ecq.modifiers) > 0 {
		_spec.Modifiers = ecq.modifiers
	}
	_spec.Node.Columns = ecq.ctx.Fields
	if len(ecq.ctx.Fields) > 0 {
		_spec.Unique = ecq.ctx.Unique != nil && *ecq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ecq.driver, _spec)
}

func (ecq *EmailCredentialQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(emailcredential.Table, emailcredential.Columns, sqlgraph.NewFieldSpec(emailcredential.FieldID, field.TypeInt))
	_spec.From = ecq.sql
	if unique := ecq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ecq.path != nil {
		_spec.Unique = true
	}
	if fields := ecq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, emailcredential.FieldID)
		for i := range fields {
			if fields[i] != emailcredential.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if ecq.withOwner != nil {
			_spec.Node.AddColumnOnce(emailcredential.FieldOwnerID)
		}
	}
	if ps := ecq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ecq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ecq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ecq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ecq *EmailCredentialQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ecq.driver.Dialect())
	t1 := builder.Table(emailcredential.Table)
	columns := ecq.ctx.Fields
	if len(columns) == 0 {
		columns = emailcredential.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ecq.sql != nil {
		selector = ecq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ecq.ctx.Unique != nil && *ecq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ecq.predicates {
		p(selector)
	}
	for _, p := range ecq.order {
		p(selector)
	}
	if offset := ecq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ecq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EmailCredentialGroupBy is the group-by builder for EmailCredential entities.
type EmailCredentialGroupBy struct {
	selector
	build *EmailCredentialQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ecgb *EmailCredentialGroupBy) Aggregate(fns ...AggregateFunc) *EmailCredentialGroupBy {
	ecgb.fns = append(ecgb.fns, fns...)
	return ecgb
}

// Scan applies the selector query and scans the result into the given value.
func (ecgb *EmailCredentialGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ecgb.build.ctx, "GroupBy")
	if err := ecgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EmailCredentialQuery, *EmailCredentialGroupBy](ctx, ecgb.build, ecgb, ecgb.build.inters, v)
}

func (ecgb *EmailCredentialGroupBy) sqlScan(ctx context.Context, root *EmailCredentialQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ecgb.fns))
	for _, fn := range ecgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ecgb.flds)+len(ecgb.fns))
		for _, f := range *ecgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ecgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ecgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EmailCredentialSelect is the builder for selecting fields of EmailCredential entities.
type EmailCredentialSelect struct {
	*EmailCredentialQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ecs *EmailCredentialSelect) Aggregate(fns ...AggregateFunc) *EmailCredentialSelect {
	ecs.fns = append(ecs.fns, fns...)
	return ecs
}

// Scan applies the selector query and scans the result into the given value.
func (ecs *EmailCredentialSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ecs.ctx, "Select")
	if err := ecs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EmailCredentialQuery, *EmailCredentialSelect](ctx, ecs.EmailCredentialQuery, ecs, ecs.inters, v)
}

func (ecs *EmailCredentialSelect) sqlScan(ctx context.Context, root *EmailCredentialQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ecs.fns))
	for _, fn := range ecs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ecs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ecs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
