// Code generated by ent, DO NOT EDIT.

package entgenerated

import (
	"api/ent/entgenerated/superuserprofile"
	"api/ent/entgenerated/user"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SuperuserProfile is the model entity for the SuperuserProfile schema.
type SuperuserProfile struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// OwnerID holds the value of the "owner_id" field.
	OwnerID int `json:"owner_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SuperuserProfileQuery when eager-loading is set.
	Edges        SuperuserProfileEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SuperuserProfileEdges holds the relations/edges for other nodes in the graph.
type SuperuserProfileEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SuperuserProfileEdges) OwnerOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.Owner == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.Owner, nil
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SuperuserProfile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case superuserprofile.FieldID, superuserprofile.FieldOwnerID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SuperuserProfile fields.
func (sp *SuperuserProfile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case superuserprofile.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sp.ID = int(value.Int64)
		case superuserprofile.FieldOwnerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value.Valid {
				sp.OwnerID = int(value.Int64)
			}
		default:
			sp.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SuperuserProfile.
// This includes values selected through modifiers, order, etc.
func (sp *SuperuserProfile) Value(name string) (ent.Value, error) {
	return sp.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the SuperuserProfile entity.
func (sp *SuperuserProfile) QueryOwner() *UserQuery {
	return NewSuperuserProfileClient(sp.config).QueryOwner(sp)
}

// Update returns a builder for updating this SuperuserProfile.
// Note that you need to call SuperuserProfile.Unwrap() before calling this method if this SuperuserProfile
// was returned from a transaction, and the transaction was committed or rolled back.
func (sp *SuperuserProfile) Update() *SuperuserProfileUpdateOne {
	return NewSuperuserProfileClient(sp.config).UpdateOne(sp)
}

// Unwrap unwraps the SuperuserProfile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sp *SuperuserProfile) Unwrap() *SuperuserProfile {
	_tx, ok := sp.config.driver.(*txDriver)
	if !ok {
		panic("entgenerated: SuperuserProfile is not a transactional entity")
	}
	sp.config.driver = _tx.drv
	return sp
}

// String implements the fmt.Stringer.
func (sp *SuperuserProfile) String() string {
	var builder strings.Builder
	builder.WriteString("SuperuserProfile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sp.ID))
	builder.WriteString("owner_id=")
	builder.WriteString(fmt.Sprintf("%v", sp.OwnerID))
	builder.WriteByte(')')
	return builder.String()
}

// SuperuserProfiles is a parsable slice of SuperuserProfile.
type SuperuserProfiles []*SuperuserProfile
