// Code generated by ent, DO NOT EDIT.

package entgenerated

import (
	"api/ent/entgenerated/predicate"
	"api/ent/entgenerated/superuserprofile"
	"api/ent/entgenerated/user"
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SuperuserProfileQuery is the builder for querying SuperuserProfile entities.
type SuperuserProfileQuery struct {
	config
	ctx        *QueryContext
	order      []superuserprofile.OrderOption
	inters     []Interceptor
	predicates []predicate.SuperuserProfile
	withOwner  *UserQuery
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*SuperuserProfile) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SuperuserProfileQuery builder.
func (spq *SuperuserProfileQuery) Where(ps ...predicate.SuperuserProfile) *SuperuserProfileQuery {
	spq.predicates = append(spq.predicates, ps...)
	return spq
}

// Limit the number of records to be returned by this query.
func (spq *SuperuserProfileQuery) Limit(limit int) *SuperuserProfileQuery {
	spq.ctx.Limit = &limit
	return spq
}

// Offset to start from.
func (spq *SuperuserProfileQuery) Offset(offset int) *SuperuserProfileQuery {
	spq.ctx.Offset = &offset
	return spq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (spq *SuperuserProfileQuery) Unique(unique bool) *SuperuserProfileQuery {
	spq.ctx.Unique = &unique
	return spq
}

// Order specifies how the records should be ordered.
func (spq *SuperuserProfileQuery) Order(o ...superuserprofile.OrderOption) *SuperuserProfileQuery {
	spq.order = append(spq.order, o...)
	return spq
}

// QueryOwner chains the current query on the "owner" edge.
func (spq *SuperuserProfileQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: spq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := spq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := spq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(superuserprofile.Table, superuserprofile.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, superuserprofile.OwnerTable, superuserprofile.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(spq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SuperuserProfile entity from the query.
// Returns a *NotFoundError when no SuperuserProfile was found.
func (spq *SuperuserProfileQuery) First(ctx context.Context) (*SuperuserProfile, error) {
	nodes, err := spq.Limit(1).All(setContextOp(ctx, spq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{superuserprofile.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (spq *SuperuserProfileQuery) FirstX(ctx context.Context) *SuperuserProfile {
	node, err := spq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SuperuserProfile ID from the query.
// Returns a *NotFoundError when no SuperuserProfile ID was found.
func (spq *SuperuserProfileQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = spq.Limit(1).IDs(setContextOp(ctx, spq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{superuserprofile.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (spq *SuperuserProfileQuery) FirstIDX(ctx context.Context) int {
	id, err := spq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SuperuserProfile entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SuperuserProfile entity is found.
// Returns a *NotFoundError when no SuperuserProfile entities are found.
func (spq *SuperuserProfileQuery) Only(ctx context.Context) (*SuperuserProfile, error) {
	nodes, err := spq.Limit(2).All(setContextOp(ctx, spq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{superuserprofile.Label}
	default:
		return nil, &NotSingularError{superuserprofile.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (spq *SuperuserProfileQuery) OnlyX(ctx context.Context) *SuperuserProfile {
	node, err := spq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SuperuserProfile ID in the query.
// Returns a *NotSingularError when more than one SuperuserProfile ID is found.
// Returns a *NotFoundError when no entities are found.
func (spq *SuperuserProfileQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = spq.Limit(2).IDs(setContextOp(ctx, spq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{superuserprofile.Label}
	default:
		err = &NotSingularError{superuserprofile.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (spq *SuperuserProfileQuery) OnlyIDX(ctx context.Context) int {
	id, err := spq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SuperuserProfiles.
func (spq *SuperuserProfileQuery) All(ctx context.Context) ([]*SuperuserProfile, error) {
	ctx = setContextOp(ctx, spq.ctx, "All")
	if err := spq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SuperuserProfile, *SuperuserProfileQuery]()
	return withInterceptors[[]*SuperuserProfile](ctx, spq, qr, spq.inters)
}

// AllX is like All, but panics if an error occurs.
func (spq *SuperuserProfileQuery) AllX(ctx context.Context) []*SuperuserProfile {
	nodes, err := spq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SuperuserProfile IDs.
func (spq *SuperuserProfileQuery) IDs(ctx context.Context) (ids []int, err error) {
	if spq.ctx.Unique == nil && spq.path != nil {
		spq.Unique(true)
	}
	ctx = setContextOp(ctx, spq.ctx, "IDs")
	if err = spq.Select(superuserprofile.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (spq *SuperuserProfileQuery) IDsX(ctx context.Context) []int {
	ids, err := spq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (spq *SuperuserProfileQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, spq.ctx, "Count")
	if err := spq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, spq, querierCount[*SuperuserProfileQuery](), spq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (spq *SuperuserProfileQuery) CountX(ctx context.Context) int {
	count, err := spq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (spq *SuperuserProfileQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, spq.ctx, "Exist")
	switch _, err := spq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("entgenerated: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (spq *SuperuserProfileQuery) ExistX(ctx context.Context) bool {
	exist, err := spq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SuperuserProfileQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (spq *SuperuserProfileQuery) Clone() *SuperuserProfileQuery {
	if spq == nil {
		return nil
	}
	return &SuperuserProfileQuery{
		config:     spq.config,
		ctx:        spq.ctx.Clone(),
		order:      append([]superuserprofile.OrderOption{}, spq.order...),
		inters:     append([]Interceptor{}, spq.inters...),
		predicates: append([]predicate.SuperuserProfile{}, spq.predicates...),
		withOwner:  spq.withOwner.Clone(),
		// clone intermediate query.
		sql:  spq.sql.Clone(),
		path: spq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (spq *SuperuserProfileQuery) WithOwner(opts ...func(*UserQuery)) *SuperuserProfileQuery {
	query := (&UserClient{config: spq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	spq.withOwner = query
	return spq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		OwnerID int `json:"owner_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SuperuserProfile.Query().
//		GroupBy(superuserprofile.FieldOwnerID).
//		Aggregate(entgenerated.Count()).
//		Scan(ctx, &v)
func (spq *SuperuserProfileQuery) GroupBy(field string, fields ...string) *SuperuserProfileGroupBy {
	spq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SuperuserProfileGroupBy{build: spq}
	grbuild.flds = &spq.ctx.Fields
	grbuild.label = superuserprofile.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		OwnerID int `json:"owner_id,omitempty"`
//	}
//
//	client.SuperuserProfile.Query().
//		Select(superuserprofile.FieldOwnerID).
//		Scan(ctx, &v)
func (spq *SuperuserProfileQuery) Select(fields ...string) *SuperuserProfileSelect {
	spq.ctx.Fields = append(spq.ctx.Fields, fields...)
	sbuild := &SuperuserProfileSelect{SuperuserProfileQuery: spq}
	sbuild.label = superuserprofile.Label
	sbuild.flds, sbuild.scan = &spq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SuperuserProfileSelect configured with the given aggregations.
func (spq *SuperuserProfileQuery) Aggregate(fns ...AggregateFunc) *SuperuserProfileSelect {
	return spq.Select().Aggregate(fns...)
}

func (spq *SuperuserProfileQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range spq.inters {
		if inter == nil {
			return fmt.Errorf("entgenerated: uninitialized interceptor (forgotten import entgenerated/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, spq); err != nil {
				return err
			}
		}
	}
	for _, f := range spq.ctx.Fields {
		if !superuserprofile.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("entgenerated: invalid field %q for query", f)}
		}
	}
	if spq.path != nil {
		prev, err := spq.path(ctx)
		if err != nil {
			return err
		}
		spq.sql = prev
	}
	if superuserprofile.Policy == nil {
		return errors.New("entgenerated: uninitialized superuserprofile.Policy (forgotten import entgenerated/runtime?)")
	}
	if err := superuserprofile.Policy.EvalQuery(ctx, spq); err != nil {
		return err
	}
	return nil
}

func (spq *SuperuserProfileQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SuperuserProfile, error) {
	var (
		nodes       = []*SuperuserProfile{}
		_spec       = spq.querySpec()
		loadedTypes = [1]bool{
			spq.withOwner != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SuperuserProfile).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SuperuserProfile{config: spq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(spq.modifiers) > 0 {
		_spec.Modifiers = spq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, spq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := spq.withOwner; query != nil {
		if err := spq.loadOwner(ctx, query, nodes, nil,
			func(n *SuperuserProfile, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	for i := range spq.loadTotal {
		if err := spq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (spq *SuperuserProfileQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*SuperuserProfile, init func(*SuperuserProfile), assign func(*SuperuserProfile, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SuperuserProfile)
	for i := range nodes {
		fk := nodes[i].OwnerID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "owner_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (spq *SuperuserProfileQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := spq.querySpec()
	if len(spq.modifiers) > 0 {
		_spec.Modifiers = spq.modifiers
	}
	_spec.Node.Columns = spq.ctx.Fields
	if len(spq.ctx.Fields) > 0 {
		_spec.Unique = spq.ctx.Unique != nil && *spq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, spq.driver, _spec)
}

func (spq *SuperuserProfileQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(superuserprofile.Table, superuserprofile.Columns, sqlgraph.NewFieldSpec(superuserprofile.FieldID, field.TypeInt))
	_spec.From = spq.sql
	if unique := spq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if spq.path != nil {
		_spec.Unique = true
	}
	if fields := spq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, superuserprofile.FieldID)
		for i := range fields {
			if fields[i] != superuserprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if spq.withOwner != nil {
			_spec.Node.AddColumnOnce(superuserprofile.FieldOwnerID)
		}
	}
	if ps := spq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := spq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := spq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := spq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (spq *SuperuserProfileQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(spq.driver.Dialect())
	t1 := builder.Table(superuserprofile.Table)
	columns := spq.ctx.Fields
	if len(columns) == 0 {
		columns = superuserprofile.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if spq.sql != nil {
		selector = spq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if spq.ctx.Unique != nil && *spq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range spq.predicates {
		p(selector)
	}
	for _, p := range spq.order {
		p(selector)
	}
	if offset := spq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := spq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SuperuserProfileGroupBy is the group-by builder for SuperuserProfile entities.
type SuperuserProfileGroupBy struct {
	selector
	build *SuperuserProfileQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (spgb *SuperuserProfileGroupBy) Aggregate(fns ...AggregateFunc) *SuperuserProfileGroupBy {
	spgb.fns = append(spgb.fns, fns...)
	return spgb
}

// Scan applies the selector query and scans the result into the given value.
func (spgb *SuperuserProfileGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, spgb.build.ctx, "GroupBy")
	if err := spgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SuperuserProfileQuery, *SuperuserProfileGroupBy](ctx, spgb.build, spgb, spgb.build.inters, v)
}

func (spgb *SuperuserProfileGroupBy) sqlScan(ctx context.Context, root *SuperuserProfileQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(spgb.fns))
	for _, fn := range spgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*spgb.flds)+len(spgb.fns))
		for _, f := range *spgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*spgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := spgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SuperuserProfileSelect is the builder for selecting fields of SuperuserProfile entities.
type SuperuserProfileSelect struct {
	*SuperuserProfileQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sps *SuperuserProfileSelect) Aggregate(fns ...AggregateFunc) *SuperuserProfileSelect {
	sps.fns = append(sps.fns, fns...)
	return sps
}

// Scan applies the selector query and scans the result into the given value.
func (sps *SuperuserProfileSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sps.ctx, "Select")
	if err := sps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SuperuserProfileQuery, *SuperuserProfileSelect](ctx, sps.SuperuserProfileQuery, sps, sps.inters, v)
}

func (sps *SuperuserProfileSelect) sqlScan(ctx context.Context, root *SuperuserProfileQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sps.fns))
	for _, fn := range sps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
