// Code generated by ent, DO NOT EDIT.

package entgenerated

import (
	"api/ent/entgenerated/emailcredential"
	"api/ent/entgenerated/loginsession"
	"api/ent/entgenerated/predicate"
	"api/ent/entgenerated/superuserprofile"
	"api/ent/entgenerated/user"
	"api/ent/entgenerated/userpublicprofile"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (uu *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetSuperuserProfileID sets the "superuser_profile" edge to the SuperuserProfile entity by ID.
func (uu *UserUpdate) SetSuperuserProfileID(id int) *UserUpdate {
	uu.mutation.SetSuperuserProfileID(id)
	return uu
}

// SetNillableSuperuserProfileID sets the "superuser_profile" edge to the SuperuserProfile entity by ID if the given value is not nil.
func (uu *UserUpdate) SetNillableSuperuserProfileID(id *int) *UserUpdate {
	if id != nil {
		uu = uu.SetSuperuserProfileID(*id)
	}
	return uu
}

// SetSuperuserProfile sets the "superuser_profile" edge to the SuperuserProfile entity.
func (uu *UserUpdate) SetSuperuserProfile(s *SuperuserProfile) *UserUpdate {
	return uu.SetSuperuserProfileID(s.ID)
}

// SetEmailCredentialID sets the "email_credential" edge to the EmailCredential entity by ID.
func (uu *UserUpdate) SetEmailCredentialID(id int) *UserUpdate {
	uu.mutation.SetEmailCredentialID(id)
	return uu
}

// SetNillableEmailCredentialID sets the "email_credential" edge to the EmailCredential entity by ID if the given value is not nil.
func (uu *UserUpdate) SetNillableEmailCredentialID(id *int) *UserUpdate {
	if id != nil {
		uu = uu.SetEmailCredentialID(*id)
	}
	return uu
}

// SetEmailCredential sets the "email_credential" edge to the EmailCredential entity.
func (uu *UserUpdate) SetEmailCredential(e *EmailCredential) *UserUpdate {
	return uu.SetEmailCredentialID(e.ID)
}

// AddLoginSessionIDs adds the "login_sessions" edge to the LoginSession entity by IDs.
func (uu *UserUpdate) AddLoginSessionIDs(ids ...int) *UserUpdate {
	uu.mutation.AddLoginSessionIDs(ids...)
	return uu
}

// AddLoginSessions adds the "login_sessions" edges to the LoginSession entity.
func (uu *UserUpdate) AddLoginSessions(l ...*LoginSession) *UserUpdate {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return uu.AddLoginSessionIDs(ids...)
}

// SetPublicProfileID sets the "public_profile" edge to the UserPublicProfile entity by ID.
func (uu *UserUpdate) SetPublicProfileID(id int) *UserUpdate {
	uu.mutation.SetPublicProfileID(id)
	return uu
}

// SetNillablePublicProfileID sets the "public_profile" edge to the UserPublicProfile entity by ID if the given value is not nil.
func (uu *UserUpdate) SetNillablePublicProfileID(id *int) *UserUpdate {
	if id != nil {
		uu = uu.SetPublicProfileID(*id)
	}
	return uu
}

// SetPublicProfile sets the "public_profile" edge to the UserPublicProfile entity.
func (uu *UserUpdate) SetPublicProfile(u *UserPublicProfile) *UserUpdate {
	return uu.SetPublicProfileID(u.ID)
}

// Mutation returns the UserMutation object of the builder.
func (uu *UserUpdate) Mutation() *UserMutation {
	return uu.mutation
}

// ClearSuperuserProfile clears the "superuser_profile" edge to the SuperuserProfile entity.
func (uu *UserUpdate) ClearSuperuserProfile() *UserUpdate {
	uu.mutation.ClearSuperuserProfile()
	return uu
}

// ClearEmailCredential clears the "email_credential" edge to the EmailCredential entity.
func (uu *UserUpdate) ClearEmailCredential() *UserUpdate {
	uu.mutation.ClearEmailCredential()
	return uu
}

// ClearLoginSessions clears all "login_sessions" edges to the LoginSession entity.
func (uu *UserUpdate) ClearLoginSessions() *UserUpdate {
	uu.mutation.ClearLoginSessions()
	return uu
}

// RemoveLoginSessionIDs removes the "login_sessions" edge to LoginSession entities by IDs.
func (uu *UserUpdate) RemoveLoginSessionIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveLoginSessionIDs(ids...)
	return uu
}

// RemoveLoginSessions removes "login_sessions" edges to LoginSession entities.
func (uu *UserUpdate) RemoveLoginSessions(l ...*LoginSession) *UserUpdate {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return uu.RemoveLoginSessionIDs(ids...)
}

// ClearPublicProfile clears the "public_profile" edge to the UserPublicProfile entity.
func (uu *UserUpdate) ClearPublicProfile() *UserUpdate {
	uu.mutation.ClearPublicProfile()
	return uu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, uu.sqlSave, uu.mutation, uu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UserUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UserUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uu *UserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if uu.mutation.SuperuserProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.SuperuserProfileTable,
			Columns: []string{user.SuperuserProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(superuserprofile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.SuperuserProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.SuperuserProfileTable,
			Columns: []string{user.SuperuserProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(superuserprofile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.EmailCredentialCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.EmailCredentialTable,
			Columns: []string{user.EmailCredentialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailcredential.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.EmailCredentialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.EmailCredentialTable,
			Columns: []string{user.EmailCredentialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailcredential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.LoginSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.LoginSessionsTable,
			Columns: []string{user.LoginSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginsession.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedLoginSessionsIDs(); len(nodes) > 0 && !uu.mutation.LoginSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.LoginSessionsTable,
			Columns: []string{user.LoginSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginsession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.LoginSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.LoginSessionsTable,
			Columns: []string{user.LoginSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginsession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.PublicProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.PublicProfileTable,
			Columns: []string{user.PublicProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userpublicprofile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.PublicProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.PublicProfileTable,
			Columns: []string{user.PublicProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userpublicprofile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uu.mutation.done = true
	return n, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetSuperuserProfileID sets the "superuser_profile" edge to the SuperuserProfile entity by ID.
func (uuo *UserUpdateOne) SetSuperuserProfileID(id int) *UserUpdateOne {
	uuo.mutation.SetSuperuserProfileID(id)
	return uuo
}

// SetNillableSuperuserProfileID sets the "superuser_profile" edge to the SuperuserProfile entity by ID if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableSuperuserProfileID(id *int) *UserUpdateOne {
	if id != nil {
		uuo = uuo.SetSuperuserProfileID(*id)
	}
	return uuo
}

// SetSuperuserProfile sets the "superuser_profile" edge to the SuperuserProfile entity.
func (uuo *UserUpdateOne) SetSuperuserProfile(s *SuperuserProfile) *UserUpdateOne {
	return uuo.SetSuperuserProfileID(s.ID)
}

// SetEmailCredentialID sets the "email_credential" edge to the EmailCredential entity by ID.
func (uuo *UserUpdateOne) SetEmailCredentialID(id int) *UserUpdateOne {
	uuo.mutation.SetEmailCredentialID(id)
	return uuo
}

// SetNillableEmailCredentialID sets the "email_credential" edge to the EmailCredential entity by ID if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableEmailCredentialID(id *int) *UserUpdateOne {
	if id != nil {
		uuo = uuo.SetEmailCredentialID(*id)
	}
	return uuo
}

// SetEmailCredential sets the "email_credential" edge to the EmailCredential entity.
func (uuo *UserUpdateOne) SetEmailCredential(e *EmailCredential) *UserUpdateOne {
	return uuo.SetEmailCredentialID(e.ID)
}

// AddLoginSessionIDs adds the "login_sessions" edge to the LoginSession entity by IDs.
func (uuo *UserUpdateOne) AddLoginSessionIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddLoginSessionIDs(ids...)
	return uuo
}

// AddLoginSessions adds the "login_sessions" edges to the LoginSession entity.
func (uuo *UserUpdateOne) AddLoginSessions(l ...*LoginSession) *UserUpdateOne {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return uuo.AddLoginSessionIDs(ids...)
}

// SetPublicProfileID sets the "public_profile" edge to the UserPublicProfile entity by ID.
func (uuo *UserUpdateOne) SetPublicProfileID(id int) *UserUpdateOne {
	uuo.mutation.SetPublicProfileID(id)
	return uuo
}

// SetNillablePublicProfileID sets the "public_profile" edge to the UserPublicProfile entity by ID if the given value is not nil.
func (uuo *UserUpdateOne) SetNillablePublicProfileID(id *int) *UserUpdateOne {
	if id != nil {
		uuo = uuo.SetPublicProfileID(*id)
	}
	return uuo
}

// SetPublicProfile sets the "public_profile" edge to the UserPublicProfile entity.
func (uuo *UserUpdateOne) SetPublicProfile(u *UserPublicProfile) *UserUpdateOne {
	return uuo.SetPublicProfileID(u.ID)
}

// Mutation returns the UserMutation object of the builder.
func (uuo *UserUpdateOne) Mutation() *UserMutation {
	return uuo.mutation
}

// ClearSuperuserProfile clears the "superuser_profile" edge to the SuperuserProfile entity.
func (uuo *UserUpdateOne) ClearSuperuserProfile() *UserUpdateOne {
	uuo.mutation.ClearSuperuserProfile()
	return uuo
}

// ClearEmailCredential clears the "email_credential" edge to the EmailCredential entity.
func (uuo *UserUpdateOne) ClearEmailCredential() *UserUpdateOne {
	uuo.mutation.ClearEmailCredential()
	return uuo
}

// ClearLoginSessions clears all "login_sessions" edges to the LoginSession entity.
func (uuo *UserUpdateOne) ClearLoginSessions() *UserUpdateOne {
	uuo.mutation.ClearLoginSessions()
	return uuo
}

// RemoveLoginSessionIDs removes the "login_sessions" edge to LoginSession entities by IDs.
func (uuo *UserUpdateOne) RemoveLoginSessionIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveLoginSessionIDs(ids...)
	return uuo
}

// RemoveLoginSessions removes "login_sessions" edges to LoginSession entities.
func (uuo *UserUpdateOne) RemoveLoginSessions(l ...*LoginSession) *UserUpdateOne {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return uuo.RemoveLoginSessionIDs(ids...)
}

// ClearPublicProfile clears the "public_profile" edge to the UserPublicProfile entity.
func (uuo *UserUpdateOne) ClearPublicProfile() *UserUpdateOne {
	uuo.mutation.ClearPublicProfile()
	return uuo
}

// Where appends a list predicates to the UserUpdate builder.
func (uuo *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	uuo.mutation.Where(ps...)
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated User entity.
func (uuo *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, uuo.sqlSave, uuo.mutation, uuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UserUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uuo *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`entgenerated: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("entgenerated: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if uuo.mutation.SuperuserProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.SuperuserProfileTable,
			Columns: []string{user.SuperuserProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(superuserprofile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.SuperuserProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.SuperuserProfileTable,
			Columns: []string{user.SuperuserProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(superuserprofile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.EmailCredentialCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.EmailCredentialTable,
			Columns: []string{user.EmailCredentialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailcredential.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.EmailCredentialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.EmailCredentialTable,
			Columns: []string{user.EmailCredentialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(emailcredential.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.LoginSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.LoginSessionsTable,
			Columns: []string{user.LoginSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginsession.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedLoginSessionsIDs(); len(nodes) > 0 && !uuo.mutation.LoginSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.LoginSessionsTable,
			Columns: []string{user.LoginSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginsession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.LoginSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.LoginSessionsTable,
			Columns: []string{user.LoginSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginsession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.PublicProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.PublicProfileTable,
			Columns: []string{user.PublicProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userpublicprofile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.PublicProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.PublicProfileTable,
			Columns: []string{user.PublicProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userpublicprofile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uuo.mutation.done = true
	return _node, nil
}
