// Code generated by ent, DO NOT EDIT.

package entgenerated

import (
	"api/ent/entgenerated/predicate"
	"api/ent/entgenerated/userpublicprofile"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserPublicProfileDelete is the builder for deleting a UserPublicProfile entity.
type UserPublicProfileDelete struct {
	config
	hooks    []Hook
	mutation *UserPublicProfileMutation
}

// Where appends a list predicates to the UserPublicProfileDelete builder.
func (uppd *UserPublicProfileDelete) Where(ps ...predicate.UserPublicProfile) *UserPublicProfileDelete {
	uppd.mutation.Where(ps...)
	return uppd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uppd *UserPublicProfileDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, uppd.sqlExec, uppd.mutation, uppd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (uppd *UserPublicProfileDelete) ExecX(ctx context.Context) int {
	n, err := uppd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uppd *UserPublicProfileDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userpublicprofile.Table, sqlgraph.NewFieldSpec(userpublicprofile.FieldID, field.TypeInt))
	if ps := uppd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, uppd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	uppd.mutation.done = true
	return affected, err
}

// UserPublicProfileDeleteOne is the builder for deleting a single UserPublicProfile entity.
type UserPublicProfileDeleteOne struct {
	uppd *UserPublicProfileDelete
}

// Where appends a list predicates to the UserPublicProfileDelete builder.
func (uppdo *UserPublicProfileDeleteOne) Where(ps ...predicate.UserPublicProfile) *UserPublicProfileDeleteOne {
	uppdo.uppd.mutation.Where(ps...)
	return uppdo
}

// Exec executes the deletion query.
func (uppdo *UserPublicProfileDeleteOne) Exec(ctx context.Context) error {
	n, err := uppdo.uppd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userpublicprofile.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uppdo *UserPublicProfileDeleteOne) ExecX(ctx context.Context) {
	if err := uppdo.Exec(ctx); err != nil {
		panic(err)
	}
}
