package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"api/config"
	"api/ent/entgenerated"
	"api/intl"
	"api/intl/intlgenerated"
	"api/lib"
	"context"

	"github.com/99designs/gqlgen/graphql"
)

// PhotoDownloadURL is the resolver for the photoDownloadUrl field.
func (r *userPublicProfileResolver) PhotoDownloadURL(ctx context.Context, obj *entgenerated.UserPublicProfile) (*string, error) {
	if obj.PhotoBlobKey == "" {
		return nil, nil
	}

	storage := lib.NewBlobStorage(&lib.BlobStorageConfig{
		AwsConfig: config.GetAwsConfig(),
	})
	url, err := storage.GetSignedExternalMediaDownloadUrl(obj.PhotoBlobKey)
	if err != nil {
		return nil, graphql.ErrorOnPath(ctx, intl.HandleIntlError(err, intlgenerated.COMMON_STRINGS__UNKNOWN_SERVER_ERROR))
	}

	return &url, nil
}
