// Code generated by ent, DO NOT EDIT.

package hook

import (
	"api/ent/entgenerated"
	"context"
	"fmt"
)

// The EmailCredentialFunc type is an adapter to allow the use of ordinary
// function as EmailCredential mutator.
type EmailCredentialFunc func(context.Context, *entgenerated.EmailCredentialMutation) (entgenerated.Value, error)

// Mutate calls f(ctx, m).
func (f EmailCredentialFunc) Mutate(ctx context.Context, m entgenerated.Mutation) (entgenerated.Value, error) {
	if mv, ok := m.(*entgenerated.EmailCredentialMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *entgenerated.EmailCredentialMutation", m)
}

// The LoginSessionFunc type is an adapter to allow the use of ordinary
// function as LoginSession mutator.
type LoginSessionFunc func(context.Context, *entgenerated.LoginSessionMutation) (entgenerated.Value, error)

// Mutate calls f(ctx, m).
func (f LoginSessionFunc) Mutate(ctx context.Context, m entgenerated.Mutation) (entgenerated.Value, error) {
	if mv, ok := m.(*entgenerated.LoginSessionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *entgenerated.LoginSessionMutation", m)
}

// The SuperuserProfileFunc type is an adapter to allow the use of ordinary
// function as SuperuserProfile mutator.
type SuperuserProfileFunc func(context.Context, *entgenerated.SuperuserProfileMutation) (entgenerated.Value, error)

// Mutate calls f(ctx, m).
func (f SuperuserProfileFunc) Mutate(ctx context.Context, m entgenerated.Mutation) (entgenerated.Value, error) {
	if mv, ok := m.(*entgenerated.SuperuserProfileMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *entgenerated.SuperuserProfileMutation", m)
}

// The UserFunc type is an adapter to allow the use of ordinary
// function as User mutator.
type UserFunc func(context.Context, *entgenerated.UserMutation) (entgenerated.Value, error)

// Mutate calls f(ctx, m).
func (f UserFunc) Mutate(ctx context.Context, m entgenerated.Mutation) (entgenerated.Value, error) {
	if mv, ok := m.(*entgenerated.UserMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *entgenerated.UserMutation", m)
}

// The UserPublicProfileFunc type is an adapter to allow the use of ordinary
// function as UserPublicProfile mutator.
type UserPublicProfileFunc func(context.Context, *entgenerated.UserPublicProfileMutation) (entgenerated.Value, error)

// Mutate calls f(ctx, m).
func (f UserPublicProfileFunc) Mutate(ctx context.Context, m entgenerated.Mutation) (entgenerated.Value, error) {
	if mv, ok := m.(*entgenerated.UserPublicProfileMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *entgenerated.UserPublicProfileMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, entgenerated.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m entgenerated.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m entgenerated.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m entgenerated.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op entgenerated.Op) Condition {
	return func(_ context.Context, m entgenerated.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m entgenerated.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m entgenerated.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m entgenerated.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk entgenerated.Hook, cond Condition) entgenerated.Hook {
	return func(next entgenerated.Mutator) entgenerated.Mutator {
		return entgenerated.MutateFunc(func(ctx context.Context, m entgenerated.Mutation) (entgenerated.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, entgenerated.Delete|entgenerated.Create)
func On(hk entgenerated.Hook, op entgenerated.Op) entgenerated.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, entgenerated.Update|entgenerated.UpdateOne)
func Unless(hk entgenerated.Hook, op entgenerated.Op) entgenerated.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) entgenerated.Hook {
	return func(entgenerated.Mutator) entgenerated.Mutator {
		return entgenerated.MutateFunc(func(context.Context, entgenerated.Mutation) (entgenerated.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []entgenerated.Hook {
//		return []entgenerated.Hook{
//			Reject(entgenerated.Delete|entgenerated.Update),
//		}
//	}
func Reject(op entgenerated.Op) entgenerated.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []entgenerated.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...entgenerated.Hook) Chain {
	return Chain{append([]entgenerated.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() entgenerated.Hook {
	return func(mutator entgenerated.Mutator) entgenerated.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...entgenerated.Hook) Chain {
	newHooks := make([]entgenerated.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
