// Code generated by mockery v2.36.1. DO NOT EDIT.

package libmocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// AuthTokenClaims is an autogenerated mock type for the AuthTokenClaims type
type AuthTokenClaims struct {
	mock.Mock
}

type AuthTokenClaims_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthTokenClaims) EXPECT() *AuthTokenClaims_Expecter {
	return &AuthTokenClaims_Expecter{mock: &_m.Mock}
}

// GetExpiresAt provides a mock function with given fields:
func (_m *AuthTokenClaims) GetExpiresAt() (time.Time, bool) {
	ret := _m.Called()

	var r0 time.Time
	var r1 bool
	if rf, ok := ret.Get(0).(func() (time.Time, bool)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// AuthTokenClaims_GetExpiresAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpiresAt'
type AuthTokenClaims_GetExpiresAt_Call struct {
	*mock.Call
}

// GetExpiresAt is a helper method to define mock.On call
func (_e *AuthTokenClaims_Expecter) GetExpiresAt() *AuthTokenClaims_GetExpiresAt_Call {
	return &AuthTokenClaims_GetExpiresAt_Call{Call: _e.mock.On("GetExpiresAt")}
}

func (_c *AuthTokenClaims_GetExpiresAt_Call) Run(run func()) *AuthTokenClaims_GetExpiresAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthTokenClaims_GetExpiresAt_Call) Return(_a0 time.Time, _a1 bool) *AuthTokenClaims_GetExpiresAt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthTokenClaims_GetExpiresAt_Call) RunAndReturn(run func() (time.Time, bool)) *AuthTokenClaims_GetExpiresAt_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserId provides a mock function with given fields:
func (_m *AuthTokenClaims) GetUserId() (int, bool) {
	ret := _m.Called()

	var r0 int
	var r1 bool
	if rf, ok := ret.Get(0).(func() (int, bool)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// AuthTokenClaims_GetUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserId'
type AuthTokenClaims_GetUserId_Call struct {
	*mock.Call
}

// GetUserId is a helper method to define mock.On call
func (_e *AuthTokenClaims_Expecter) GetUserId() *AuthTokenClaims_GetUserId_Call {
	return &AuthTokenClaims_GetUserId_Call{Call: _e.mock.On("GetUserId")}
}

func (_c *AuthTokenClaims_GetUserId_Call) Run(run func()) *AuthTokenClaims_GetUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthTokenClaims_GetUserId_Call) Return(_a0 int, _a1 bool) *AuthTokenClaims_GetUserId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthTokenClaims_GetUserId_Call) RunAndReturn(run func() (int, bool)) *AuthTokenClaims_GetUserId_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthTokenClaims creates a new instance of AuthTokenClaims. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthTokenClaims(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthTokenClaims {
	mock := &AuthTokenClaims{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
