-- Create "ent_types" table
CREATE TABLE "ent_types" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "type" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "ent_types_type_key" to table: "ent_types"
CREATE UNIQUE INDEX "ent_types_type_key" ON "ent_types" ("type");
-- Create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 12884901888), "name" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "users_name_key" to table: "users"
CREATE UNIQUE INDEX "users_name_key" ON "users" ("name");
-- Create "email_credentials" table
CREATE TABLE "email_credentials" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "email" character varying NOT NULL, "algorithm" character varying NOT NULL, "password_hash" bytea NOT NULL, "owner_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "email_credentials_users_email_credential" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "email_credentials_email_key" to table: "email_credentials"
CREATE UNIQUE INDEX "email_credentials_email_key" ON "email_credentials" ("email");
-- Create index "email_credentials_owner_id_key" to table: "email_credentials"
CREATE UNIQUE INDEX "email_credentials_owner_id_key" ON "email_credentials" ("owner_id");
-- Create "login_sessions" table
CREATE TABLE "login_sessions" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 4294967296), "last_login_time" timestamptz NOT NULL, "owner_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "login_sessions_users_login_sessions" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "superuser_profiles" table
CREATE TABLE "superuser_profiles" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 8589934592), "owner_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "superuser_profiles_users_superuser_profile" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "superuser_profiles_owner_id_key" to table: "superuser_profiles"
CREATE UNIQUE INDEX "superuser_profiles_owner_id_key" ON "superuser_profiles" ("owner_id");
-- Add pk ranges for ('email_credentials'),('login_sessions'),('superuser_profiles'),('users') tables
INSERT INTO "ent_types" ("type") VALUES ('email_credentials'), ('login_sessions'), ('superuser_profiles'), ('users');
