quiet: False
with-expecter: True
filename: "{{.InterfaceName}}.go"
mockname: "{{.InterfaceName}}"
dir: "{{.InterfaceDir}}/{{.PackageName}}mocks"
outpkg: "{{.PackageName}}mocks"
packages:
  api/config:
    interfaces:
      AwsConfig:
      HmacConfig:
      UrlConfig:
  api/lib:
    interfaces:
      AuthTokenClaims:
      BlobStorage:
      CookieReader:
      EmailCredentialManager:
      EmailSignupJwtTokenFactory:
      EmailSignupTokenClaims:
      HttpErrorWriter:
      LoginSessionFactory:
      Logger:
      Mailer:
      RefreshTokenClaims:
      ResetPasswordTokenClaims:
      UserFactory:
      UserTokenFactory:
  api/lib/aws:
    interfaces:
      S3Client:
  api/privacy/viewer:
    interfaces:
      Viewer: